%!Rnw root = ../../Master.Rnw

\chapter{Workshops}
\label{chap:ch13}

\pagebreak

\section{Workshop 1}         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{center}
\begin{flushleft}\textbf{ \large \hfill Workshop 1 Fall 2016 }\end{flushleft}

\vspace{4mm}
\makebox[\textwidth]{Name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{Instructor's name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{(Week 1: Due date: \underline{\phantom{xxxxxxxxxxxx}}) }
\end{center} 



\begin{exercises}

    \begin{exercise}  % 1-1    
    
      A psychologist wants to know if adults with normal vision can be fooled by a certain optical illusion.  She recruits 50 students from her PSY 120 class and finds that 42 of them are fooled by the illusion.  The population in this study is 
      
%       \begin{enumerate}
%       \item all adults with normal vision.
%       \item the 42 students who were fooled.
%       \item the 50 students who served as subjects.
%       \item all students in the PSY 120 class. 
%       \end{enumerate}
      \vspace{8mm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \begin{solution}
      all adults with normal vision.
    \end{solution}

      \begin{exercise}  % 1-2
      
      You want to know the opinions of American school teachers about establishing a national test for high school graduation.  You obtain a list of the members of the National Education Association (the largest teachers' union) and mail a questionnaire to 2500 teachers chosen at random from this list.  In all 1,347 teachers return the questionnaire.  The sample is 
      
%       \begin{enumerate}
%       \item all members of the National Education Association. 
%       \item all American school teachers. 
%       \item the 1,347 teachers who mail back the questionnaire. 
%       \item the 2,500 teachers to whom you mailed the questionnaire. 
%       \end{enumerate}
      \vspace{8mm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
      the 1,347 teachers who mail back the questionnaire. 
    \end{solution}  

      \begin{exercise}  % 1-3

      You measure the age (years), weight (pounds), and marital status (single, married, divorced, or widowed) of 1,400 women.  How many variables did you measure? 
      
%       \begin{enumerate}
%       \item one
%       \item two
%       \item three
%       \item 1,400
%       \end{enumerate}
      \vspace{8mm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
      three
    \end{solution}  

      \begin{exercise}  % 1-4
      
      Following are data on the populations and numbers of death row prisoners for several states.

% Requires the booktabs if the memoir class is not being used
\begin{table}[htbp]
   \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
   \begin{tabular}{@{} lrr @{}} \hline % Column formatting, @{} suppresses leading/trailing space
    State & Population (thousands) & Death Row Prisoners \\ \hline 
    California & 28,168 & 247 \\ 
    Florida & 12,377 & 294 \\
    Illinois & 11,544 & 120 \\
    Nevada & 1,060 & 45 \\ \hline 
   \end{tabular}

\end{table} 

      Which state has the highest number of death row prisoners relative to the size of its population?  
      
%       Question options:
% 
%       \begin{enumerate}
%       \item California
%       \item Florida
%       \item Illinois
%       \item Nevada
%       \end{enumerate}
      \vspace{8mm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      Rate of California is 
      <<results="asis", echo=FALSE>>=
        rate <- 247/28168*1000; rate
        rm(rate)
      @  
      Rate of Florida is 
      <<results="asis", echo=FALSE>>=
        rate <- 294/12377*1000; rate
        rm(rate)
      @  
      Rate of Illinois is 
      <<results="asis", echo=FALSE>>=
        rate <- 120/11544*1000; rate
        rm(rate)
      @  
      Rate of Nevada is 
      <<results="asis", echo=FALSE>>=
        rate <- 45/1060*1000; rate
        rm(rate)
      @  
      
        Therefore, Nevada has the highest number of death row prisoners.
        
    \end{solution} 

      \begin{exercise}  % 1-5
      
      Michelle's income two years ago was \$420,000.  Last year her income was only \$100,000.  The percent change in Michelle's income was 


%       Question options:
% 
%       \begin{enumerate}
%       \item 76.2\% decrease
%       \item 23.8\% decrease 
%       \item 320\% decrease
%       \item 31.3\% decrease
%       \end{enumerate}
  
      \vspace{8mm}   
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      Rate of Michelle's income is 
      <<results="asis", echo=FALSE>>=
        pc <- (100000 - 420000) / 420000 *100; pc
        rm(pc)
      @  
      
    \end{solution} 

      \begin{exercise}  % 1-6
      
      A student reports that of a sample of 200 college undergraduates, 37\% were female and 41\% were male.  We know that the student has made a mistake because 

%       Question options:
% 
%       \begin{enumerate}
%       \item 37% plus 41% is not 100%.
%       \item the percentages of males and females would be closer together in a true sample.
%       \item of the possibility of response error. 
%       \item it is highly unlikely that a sample of 200 undergraduates would have as few as 37% females. 
%       \end{enumerate}
  
      \vspace{8mm}    
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      <<results="asis", echo=FALSE>>=
        37 + 41
      @  
        is not equal to 100\%.
        
    \end{solution} 

      \begin{exercise}  % 1-7
      
      You are writing an article for the college newspaper about the cost of attending college.  You want to make a graph to compare costs at your school and three similar schools.  A good choice of a graph would be a 


%       Question options:
% 
%       \begin{enumerate}
%       \item histogram
%       \item box plot
%       \item bar chart 
%       \item pie chart
%       \end{enumerate}
  
      \vspace{8mm}    
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    A good choice of a graph would be a bar chart. 
      
    \end{solution} 

      \begin{exercise}  % 1-8
      
      When dealing with financial data (such as salaries or lawsuit settlements), we often find that the shape of the distribution is
\underline{\phantom{xxxxxxxxxx}}.  When the distribution has this shape, the \underline{\phantom{xxxxxxxxxx}} is pulled toward the long tail of the distribution, but the \underline{\phantom{xxxxxxxxxx}} is less affected.  The sequence of words to correctly complete this statement is: 

%       Question options:
% 
%       \begin{enumerate}
%       \item right-skewed, mean, standard deviation. 
%       \item right-skewed, median, mean.
%       \item right skewed, mean, median.  
%       \item left-skewed, mean, median. 
%       \end{enumerate}
  
      \vspace{8mm}    
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      right skewed, mean, median.
      
    \end{solution} 

      \begin{exercise}  % 1-9
      
      For categorical variables (like a person's occupation or sex) it only makes sense to speak of \underline{\phantom{xxxxxxxxxx}}.
It makes no sense to speak of the \underline{\phantom{xxxxxxxxxx}} or the \underline{\phantom{xxxxxxxxxx}} sex.  The sequence of words to correctly complete this statement is 

%       Question options:
% 
%       \begin{enumerate}
%       \item counts or percents, mean, median.  
%       \item mode, mean, median. 
%       \item median, mean, mode.   
%       \item quartiles, mean, median. 
%       \end{enumerate}
  
      \vspace{8mm}    
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      counts or percents, mean, median.
      
    \end{solution} 

      \begin{exercise}  % 1-10
      
      What is the first quartile of the observations 
      
      \begin{table}[htbp]
   \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
   \begin{tabular}{@{} ccccccccccc @{}} \hline % Column formatting, @{} suppresses leading/trailing space
   2 & -2 & 1 & -1 & 1 & 0 & 0 & 3 & 0 & 2 & 3  \\ \hline
   \end{tabular}
\end{table}  
      
      

%       Question options:
% 
%       \begin{enumerate}
%       \item -1
%       \item 0 
%       \item 1  
%       \item 2   
%       \end{enumerate}
  
      \vspace{9mm}    
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
      <<results="asis", echo=FALSE>>=
      dat1<- c(2, -2, 1, -1, 1, 0, 0, 3, 0, 2, 3)  
      summary(dat1)
      rm(dat1)
      @
      
      $Q_1 = 0$ 
      
    \end{solution} 

\end{exercises}

\pagebreak 

\section{Workshop 2} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{center}
\begin{flushleft}\textbf{ \large \hfill Workshop 2 Fall 2016 }\end{flushleft}

\vspace{4mm}
\makebox[\textwidth]{Name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{Instructor's name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{(Week 2: Due date: \underline{\phantom{xxxxxxxxxxxx}}) }
\end{center} 



\begin{exercises}

    \begin{exercise}  % 2-1
    
      Here are the number of hours that each of a group of students studied for this exam:

\begin{table}[htbp]
   \centering
   %\topcaption{Table captions are better up top} % requires the topcapt package
   \begin{tabular}{@{} cccccccccc @{}} \hline % Column formatting, @{} suppresses leading/trailing space
    2  & 4  & 22  & 2 &  1  & 4 &  1  & 5 &  5  & 4 \\ \hline
   \end{tabular}

\end{table}  

      What is the third quartile of the number of study hours? (Use the method used in Chapter 4 slides) 
      
%       Question options:      
%       \begin{enumerate}
%       \item 1.5 
%       \item 5.5
%       \item 5.0
%       \item 2
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    <<results="asis", echo=FALSE>>=
      dat1 <- c(2  , 4  , 22  , 2 ,  1  , 4 ,  1  , 5 ,  5  , 4)
      summary(dat1)
      rm(dat1)
    @  
     
      Therefore, $Q_3 = 5$
      
    \end{solution}

    \begin{exercise}  % 2-2
    
      Using the scenario from exercise 2-1, what is the standard deviation of the number of study hours? 
      
%       Question options:      
%       \begin{enumerate}
%       \item 5.8 
%       \item 38
%       \item 6.2
%       \item 34.2
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    Therefore, s =
    <<results="asis", echo=FALSE>>=
      dat1 <- c(2  , 4  , 22  , 2 ,  1  , 4 ,  1  , 5 ,  5  , 4)
      sd(dat1)
      rm(dat1)
    @  
     
    \end{solution}
    \vspace{2mm}
    \begin{exercise}  % 2-3
    
      Using the scenario from exercise 2-1, what is the interquartile range of the number of study hours?
      
%       Question options:      
%       \begin{enumerate}
%       \item 3
%       \item 5
%       \item 2
%       \item 4
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    Therefore, IQR =
    <<results="asis", echo=FALSE>>=
      dat1 <- c(2  , 4  , 22  , 2 ,  1  , 4 ,  1  , 5 ,  5  , 4)
      
      IQR(dat1)
      rm(dat1)
    @  
     
    \end{solution}

    \begin{exercise}  % 2-4
    
      Using the data from exercise 2-1, the data contain one high outlier (22 hours).  Which of your results (third quartile, standard deviation, interquartile range) for the three previous exercises would change if this were five (5) hours instead of 22 hours?  (You do not need to calculate new values.) 
      
%       Question options:      
%       \begin{enumerate}
%       \item only the standard deviation would change.
%       \item the third quartile and the standard deviation would change.
%       \item all three would change.
%       \item the interquartile range and the standard deviation would change.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
        Standard deviation would change.
    
     
    \end{solution}
    
    \begin{exercise}  % 2-5
    
      (For this exercise, consider the five central tendency variables).  For a distribution that is skewed to the left, usually,

%       Question options:      
%       \begin{enumerate}
%       \item the median will be larger than the mean.
%       \item the first quartile will be larger than the third quartile.
%       \item the mean will be larger than the median.
%       \item the standard deviation will be negative.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      The median will be larger than the mean if the distribution is left skewed.
     
    \end{solution}
        
    \begin{exercise}  % 2-6
        
      You have calculated the value, of the standard deviation for a set of data, is -2.5.  You can conclude that  

%       Question options:      
%       \begin{enumerate}
%       \item you made an error in your calculations.
%       \item all of the observations in the dataset are negative.
%       \item there is very little variation in the dataset.
%       \item the data are skewed to the left.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
     
      You made an error in your calculations.
     
    \end{solution}
    
      \begin{exercise}  % 2-7
        
        You calculate that the standard deviation of a set of observations is zero (0).  This tells you that 

%       Question options:      
%       \begin{enumerate}
%       \item all the observations have the same value.
%       \item the mean must also be zero (0).
%       \item all the observations must be zero (0).
%       \item you made an error.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
        all the observations have the same value.
    
    \end{solution}
    
    \begin{exercise}  % 2-8
       
      <<f13_2_1, echo=FALSE, fig.pos="ht", fig.align="center",  fig.width=3.3, fig.height=3.3, fig.cap="Comparing Calories">>=
        poul1 <- runif(17,min=85,max=170)
        meat1 <- runif(17,min=105,max=195)
        beef1 <- runif(20,min=110,max=190)
        calories <- numeric(54)
        calories[1:17] <- poul1[1:17]
        calories[18:34] <- meat1[1:17]
        calories[35:54] <- beef1[1:20]
        type1 <- c(rep("Poul",17),rep("Meat",17),rep("Beef",20))
        boxplot(calories ~ type1, xlab="Protein Type", ylab="Calories")
        rm( poul1, meat1, beef1, calories, type1)
     @ 
        
Above are box plots of the number of calories in 20 brands of beef hotddogs, 17 brands of meat hotdogs, and 17 brands of poultry 
hotdogs.  The plot shows that 

          
%       \begin{enumerate}
%       \item most poultry hotdogs brands have fewer calories that most beef and meat hotdogs, but a few poultry hotdogs have more calories that the median beef and meat hotdogs.
%       \item about half of poultry hotdogs brands have fewer calories than the median for beef and meat hotdogs brands.
%       \item all poultry hotdog brands have fewer calories than the median for beef and meat hotdog brands.
%       \item hotdog type is not helpful in predicting calories, because some hotdog brands of each type are high and some of each type are low.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    The plot shows that most poultry hotdogs brands have fewer calories that most beef and meat hotdogs, but a few poultry hotdogs have more calories that the median beef and meat hotdogs.
     
    \end{solution}
    
    \begin{exercise}  % 2-9
    
      The box in each box plot marks   

%       Question options:      
%       \begin{enumerate}
%       \item the span one standard deviation on each side of the mean.
%       \item the range covered by the middle half of the data.
%       \item the span two standard deviations on each side of the mean.
%       \item the range covered by the middle three-quarters of the data. 
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
        
        The box in each box plot marks the range covered by the middle half of the data.

    \end{solution}

    \begin{exercise}  % 2-10
    
    
    <<f13_2_2, echo=FALSE, fig.pos="ht", fig.align="center", fig.width=3.3, fig.height=3.3, fig.cap="Mean Comparison">>=

  x10<-seq(10,35,.1)
  y10<-dnorm(x10,mean=19.2,sd=1.52)
  plot(x10,y10, type="l")
  y11<-dnorm(x10,mean=23.8,sd=3.68)
  lines(x10,y11)
  text(25,.2,"A")
  lines(c(21,25),c(.15,.18))
  text(30,.12,"B")
  lines(c(27,30),c(.08,.10))
  
  rm(x10,y10,y11)
@

    The above graphs of two bell-shaped / symmetric distributions, curve A and curve B.  What is the best description of the relation between curve A and curve B.

%       Question options:      
%       \begin{enumerate}
%       \item mean of curve A is less than mean of curve B and standard deviation of curve A is less than standard deviation of curve B.
%       \item mean of curve A is less than mean of curve B and standard deviation of curve A is greater than standard deviation of curve B.
%       \item mean of curve A is greater than mean of curve B and standard deviation of curve A is less than standard deviation of curve B.
%       \item mean of curve A is greater than mean of curve B and standard deviation of curve A is greater than standard deviation of curve B.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    mean of curve A is less than mean of curve B and standard deviation of curve A is less than standard deviation of curve B.
    
    \end{solution}
    
    
\end{exercises}

\pagebreak

\section{Workshop 3} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{center}
\begin{flushleft}\textbf{ \large \hfill Workshop 3 Fall 2016 }\end{flushleft}

\vspace{4mm}
\makebox[\textwidth]{Name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{Instructor's name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{(Week 3: Due date: \underline{\phantom{xxxxxxxxxxxx}}) }
\end{center} 



\begin{exercises}

    \begin{exercise}  % 3-1
    
<<f13_3_1, echo=FALSE, fig.pos="ht", fig.align="center", fig.width=3, fig.height=3, fig.cap="Mean Comparison">>=

  x10<-seq(10,85,.1)
  y10<-dnorm(x10,mean=50,sd=10)
  plot(x10,y10, type="l")
  
@
    
      The mean of the normal distribution is 
      
%       Question options:      
%       \begin{enumerate}
%       \item 10
%       \item 50
%       \item 60
%       \item 70
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      The mean of the normal distribution is 50.
      
    \end{solution}
    
    \begin{exercise}  % 3-2
    
%' <<f13_3_2, echo=FALSE, fig.pos="ht", fig.align="center", fig.width=3, fig.height=3, fig.cap="Mean Comparison">>=
%' 
%'   plot(x10,y10, type="l")
%'   
%' @
    
      Using Figure 13.3, the standard deviation of the normal distribtion is (Hint: use the empirical rule.)
      
%       Question options:      
%       \begin{enumerate}
%       \item 100
%       \item 70
%       \item 20
%       \item 10
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      The standard deviation of the normal distribution is 10.
      
    \end{solution}    
    
    \begin{exercise}  % 3-3
    
      A number with 60 percent of the data above it is 

%       Question options:      
%       \begin{enumerate}
%       \item the $60^{th}$ percentile.
%       \item the $40^{th}$ percentile.
%       \item always smaller than the mean.
%       \item always larger than the mean.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    A number with 60 percent of the data above it is 
    the $40^{th}$ percentile.

    \end{solution}
    
        
    \begin{exercise}  % 3-4
        
      Scores of adults on the Wechsler Adults Intelligence Scale (a common IQ test) follow a normal distribution.  The middle 99.7\% of scores on this test range from 55 to 145.  What is the standard deviation of the test scores?  
	
%       Question options:      
%       \begin{enumerate}
%       \item 7.5 points
%       \item 10 points
%       \item 15 points
%       \item 20 points
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    the standard deviation of the test scores is
    <<results="asis", echo=FALSE>>=
        sd1 <- (145 - 55) / 6; sd1 
    @  
     
    \end{solution}
    
    \begin{exercise}  % 3-5
        
      What percent of the observations from a normal distribution lie between the standard scores $z = -1$ and $z = 2$?
      
%       Question options:      
%       \begin{enumerate}
%       \item 16\%
%       \item 47.5\%
%       \item 61\%
%       \item 81.9\%
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      $P[ -1 < z < 2 ] = P[z < 2] - P[ z < -1 ] = 
    <<results="asis", echo=FALSE>>=
        pnorm(2)- pnorm(-1)
    @  
     
    \end{solution}    
    
    \begin{exercise}  % 3-6
        
      Entomologist Heinz Kaefer has a colony of bongo spiders in his lab.  There are 1,000 adult spiders in the colony, and their weights are normally distributed with mean 11 grams and standard deviation 2 grams.  About how many spiders in the colony weigh more than 12 grams?
    
%       Question options:      
%       \begin{enumerate}
%       \item 160
%       \item 310
%       \item 690
%       \item 840
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
      $P[ \bar{x} > 12 ] \times 1000 = (1 - P[\bar{x} < 12]) \times 1000 =  (1 - P[z < .5]) \times 1000 =$
    <<results="asis", echo=FALSE>>=
        (1 - pnorm(.5)) * 1000
    @  
     
    \end{solution}    
    
    \begin{exercise}  % 3-7
        
      The distribution of scores on an SAT exam is normal, with mean 500 and standard deviation 100.  So the median score on the exam 
      
%       Question options:      
%       \begin{enumerate}
%       \item is less than 500.
%       \item is equal to 500.
%       \item is greater than 500.
%       \item could be anywhere between 400 and 600.
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \begin{solution}
    
    So the median score on the exam is equal to 500.
     
    \end{solution}
    
    \begin{exercise}  % 3-8
           
     Scores on teh Graduate Record Examination (GRE) follow a normal distribution.  Jennifer's score is 2 standard deviations above the mean.  About what percent of scores are higher than Jennifer's?
       
%       Question options:      
%       \begin{enumerate}
%       \item 2.5\%
%       \item 5\%
%       \item 16\%
%       \item 50\%
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    The percent of scores are higher is  
    <<results="asis", echo=FALSE>>=
        1 - pnorm(1.96)
    @  
     
    \end{solution}
    
    
    
    \begin{exercise}  % 3-9
    
      Suppose that the distribution of Writing SAT scores from your state this year is normally distributed with mean 480 and standard deviation 110 for males. 
      
      If someone who scores 700 or higher on the Writing SAT can be considered exceptional, the proportion of exceptional students among male SAT takers is about 
    
%       Question options:      
%       \begin{enumerate}
%       \item 1.5\%
%       \item 2.28\%
%       \item 5\%
%       \item 47.72\%
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    the proportion of exceptional students among male SAT takers is about 
    <<results="asis", echo=FALSE>>=
        z1 <- (700 - 480)/110
        1 - pnorm(z1)
        rm(z1)
    @  
     
    \end{solution}

    \begin{exercise}  % 3-10
      
      Suppose that the distribution of Writing SAT scores from your state this year is normally distributed with mean 480 and standard deviation 110 for males. 
      
      Mike took the Writing SAT and scored 670.  He did better than approximately \underline{\phantom{xxxxxxxx}} \% of male students taking the test. 
       
      
%       Question options:      
%       \begin{enumerate}
%       \item 4.2
%       \item 45.8
%       \item 95.8
%       \item 99.9
%       \end{enumerate}
      \vspace{1cm}
      \framebox[6cm][l]{ Answer: }
      
    \end{exercise}
    \vspace{1mm}
    \begin{solution}
    
    Mike did better than   
    <<results="asis", echo=FALSE>>=
        z1 <- (670 - 480)/110
        (pnorm(z1))*100
    @  
    \% of his male peers.
    
    \end{solution}
    
\end{exercises}

\pagebreak

\section{Workshop 4} %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{center}
\begin{flushleft}\textbf{ \large \hfill Workshop 4 Fall 2016 }\end{flushleft}

\vspace{4mm}
\makebox[\textwidth]{Name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{Instructor's name:\enspace\hrulefill}
\vspace{4mm}
\makebox[\textwidth]{(Week 4: Due date: \underline{\phantom{xxxxxxxxxxxx}}) }
\end{center} 

\begin{exercises}

  \begin{exercise}
  lkljlj
  \end{exercise}
  \begin{solution}
  
  lkjljl
  \end{solution}


\end{exercises}
